sudo: required
services:
  - docker

before_install:
  - sudo apt-get update

before_script:
  - docker pull openvinoincluit/openvino:latest || true
script:
  - docker run --name openvinocont -t -d openvinoincluit/openvino:latest
  - docker exec openvinocont git clone https://github.com/incluit/OpenVino-For-SmartCity
  - docker exec openvinocont bash -c 'source /opt/intel/computer_vision_sdk/bin/setupvars.sh && cd /app/OpenVino-For-SmartCity && git checkout "OpenVINO<=2019R1" && mkdir build && cd build && source /app/OpenVino-For-SmartCity/scripts/setupenv.sh && cmake .. && make'
  - docker exec openvinocont bash -c 'cd /app/OpenVino-For-SmartCity/build && build-wrapper-linux-x86-64 --out-dir bw-output make clean all'
  - docker exec openvinocont bash -c 'cd /app/OpenVino-For-SmartCity/build && sonar-scanner -Dsonar.projectKey=incluit_OpenVino-For-SmartCity -Dsonar.organization=incluit -Dsonar.sources=. -Dsonar.cfamily.build-wrapper-output=bw-output -Dsonar.host.url=https://sonarcloud.io -Dsonar.projectBaseDir=../src -Dproject.home=../src -Dsonar.login=b4374702344cc6949ebbbafcad6b4ea1d002ba1d'

after_script:
  - docker images
